# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resultInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=15)),
                ('contactdate', models.CharField(max_length=15)),
                ('contactstatus', models.CharField(max_length=20)),
                ('casestatus', models.CharField(max_length=10)),
                ('expectdate', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('tel', models.CharField(max_length=15)),
                ('money', models.IntegerField()),
                ('deadline', models.CharField(max_length=15)),
                ('delay', models.IntegerField()),
                ('utype', models.IntegerField()),
                ('importdate', models.CharField(max_length=15)),
                ('flag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versions', models.CharField(max_length=20)),
            ],
        ),
    ]
